---
#playbook for running the network test
- hosts: server
  remote_user: ubuntu
  become: yes
  become_user: root
  
  tasks:
    - name: tasks to be executed on server
      block:
      - name: start iperf3 server as daemon  
        shell: iperf3 --server --daemon
      when: inventory_hostname in groups['server'] 

- hosts: clients
  remote_user: ubuntu
  become: yes
  become_user: root     
  tasks:
  - name: include perf role
    include: iperf-test.yml
    loop:
        - with_items: "{{ inventory_hostname  }}"
  vars:
    server : "{{ groups['server'][0] }}"

  