---
#playbook for running the network test
- hosts: server
  remote_user: ubuntu
  become: yes
  become_user: root
  
  tasks:
    - name: tasks to be executed on server
      block:
      - name: start iperf3 server as daemon  
        shell: iperf3 --server --daemon
      when: inventory_hostname in groups['server'] 

- hosts: clients
  remote_user: ubuntu
  become: yes
  become_user: root     
  tasks:

      - name: execute iperf test
        shell: "iperf3 -c {{ server }} --logfile /var/log/Iperf3_logs/Iperf3_results_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.log"
  vars:
    server : "{{ groups['server'][0] }}"

